install:
  # Check dead links
  - sudo apt-get install npm
  - sudo npm install -g markdown-link-check
  # proselint
  - sudo pip install proselint
  # LaTex, pandoc
  # No pdflatex?
  - sudo apt-get install pandoc texlive-latex-recommended texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended texlive-extra-utils texlive-humanities texlive-full pgf

script:
  # Check dead links
  - ./check_dead_links
  # proselint
  - proselint README.md
  - pandoc article.tex -o article.txt
  - proselint article.txt
  # Can article be converted to PDF?
  - ./create_article
  # List possible spelling errors
  - spell article.tex
  # Count words, must be below 3000 for 'Applications'
  - wc article.txt --words 
